/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    tasks: Task;
    notifications: Notification;
    clients: Client;
    visits: Visit;
    'chat-rooms': ChatRoom;
    'chat-messages': ChatMessage;
    'design-requests': DesignRequest;
    'code-reviews': CodeReview;
    'time-entries': TimeEntry;
    'login-logs': LoginLog;
    'firewall-rules': FirewallRule;
    'push-subscriptions': PushSubscription;
    'task-comments': TaskComment;
    'task-activities': TaskActivity;
    'project-files': ProjectFile;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    projects: {
      tasks: 'tasks';
    };
    clients: {
      visits: 'visits';
    };
    'chat-rooms': {
      messages: 'chat-messages';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    visits: VisitsSelect<false> | VisitsSelect<true>;
    'chat-rooms': ChatRoomsSelect<false> | ChatRoomsSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    'design-requests': DesignRequestsSelect<false> | DesignRequestsSelect<true>;
    'code-reviews': CodeReviewsSelect<false> | CodeReviewsSelect<true>;
    'time-entries': TimeEntriesSelect<false> | TimeEntriesSelect<true>;
    'login-logs': LoginLogsSelect<false> | LoginLogsSelect<true>;
    'firewall-rules': FirewallRulesSelect<false> | FirewallRulesSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    'task-comments': TaskCommentsSelect<false> | TaskCommentsSelect<true>;
    'task-activities': TaskActivitiesSelect<false> | TaskActivitiesSelect<true>;
    'project-files': ProjectFilesSelect<false> | ProjectFilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'system-settings': SystemSetting;
  };
  globalsSelect: {
    'system-settings': SystemSettingsSelect<false> | SystemSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  phone?: string | null;
  avatar?: (string | null) | Media;
  role: 'super-admin' | 'supervisor' | 'auditor' | 'sales-rep' | 'programmer' | 'designer' | 'social-media-manager';
  isActive?: boolean | null;
  telegramChatId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  description?: string | null;
  status: 'planning' | 'active' | 'on-hold' | 'completed' | 'cancelled';
  estimatedHours?: number | null;
  startDate?: string | null;
  endDate?: string | null;
  manager?: (string | null) | User;
  members?: (string | User)[] | null;
  tasks?: {
    docs?: (string | Task)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'programming' | 'field-visit' | 'design' | 'general';
  priority: 'urgent' | 'high' | 'medium' | 'low';
  status: 'new' | 'in-progress' | 'in-review' | 'completed' | 'cancelled';
  assignee?: (string | null) | User;
  assignedBy?: (string | null) | User;
  project?: (string | null) | Project;
  dueDate?: string | null;
  recurrence?: ('none' | 'daily' | 'weekly' | 'monthly') | null;
  githubRepo?: string | null;
  githubBranch?: string | null;
  /**
   * المهام التي يجب إنجازها قبل هذه المهمة
   */
  dependencies?: (string | Task)[] | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  recipient: string | User;
  type: 'task-assigned' | 'task-updated' | 'comment' | 'security-alert' | 'visit' | 'system';
  title: string;
  message: string;
  isRead?: boolean | null;
  link?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  name: string;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  city?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  tags?: ('vip' | 'new' | 'regular' | 'prospect' | 'inactive')[] | null;
  notes?: string | null;
  uuid?: string | null;
  createdBy?: (string | null) | User;
  visits?: {
    docs?: (string | Visit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits".
 */
export interface Visit {
  id: string;
  client: string | Client;
  representative: string | User;
  status: 'checked-in' | 'checked-out' | 'cancelled';
  checkInTime: string;
  checkOutTime?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  checkInLocation?: [number, number] | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  checkOutLocation?: [number, number] | null;
  checkInPhoto?: (string | null) | Media;
  distance?: number | null;
  /**
   * يتم التحقق تلقائياً من صحة الموقع
   */
  isValid?: boolean | null;
  notes?: string | null;
  syncedFromOffline?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-rooms".
 */
export interface ChatRoom {
  id: string;
  name: string;
  members: (string | User)[];
  createdBy?: (string | null) | User;
  messages?: {
    docs?: (string | ChatMessage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: string;
  room: string | ChatRoom;
  sender: string | User;
  content?: string | null;
  type?: ('text' | 'image' | 'file') | null;
  attachment?: (string | null) | Media;
  mentions?: (string | User)[] | null;
  replyTo?: (string | null) | ChatMessage;
  reactions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isPinned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-requests".
 */
export interface DesignRequest {
  id: string;
  title: string;
  description?: string | null;
  platform: ('instagram' | 'twitter' | 'facebook' | 'tiktok' | 'linkedin' | 'snapchat')[];
  status: 'requested' | 'in-progress' | 'in-review' | 'approved' | 'rejected' | 'published';
  designer?: (string | null) | User;
  requestedBy?: (string | null) | User;
  dueDate?: string | null;
  designs?:
    | {
        image: string | Media;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code-reviews".
 */
export interface CodeReview {
  id: string;
  title: string;
  task?: (string | null) | Task;
  submittedBy?: (string | null) | User;
  reviewer?: (string | null) | User;
  status: 'pending' | 'in-review' | 'approved' | 'rejected' | 'changes-requested';
  githubRepo?: string | null;
  githubBranch?: string | null;
  githubPR?: string | null;
  description?: string | null;
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries".
 */
export interface TimeEntry {
  id: string;
  user: string | User;
  task: string | Task;
  startTime: string;
  endTime?: string | null;
  duration?: number | null;
  description?: string | null;
  isRunning?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs".
 */
export interface LoginLog {
  id: string;
  user?: (string | null) | User;
  email?: string | null;
  success?: boolean | null;
  ip?: string | null;
  userAgent?: string | null;
  country?: string | null;
  isTor?: boolean | null;
  isVPN?: boolean | null;
  isProxy?: boolean | null;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firewall-rules".
 */
export interface FirewallRule {
  id: string;
  type: 'ip' | 'ip-range' | 'country';
  /**
   * مثال: 192.168.1.1 أو 192.168.1.0/24 أو SA
   */
  value: string;
  action: 'block' | 'allow';
  description?: string | null;
  isActive?: boolean | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: string;
  user: string | User;
  endpoint: string;
  subscription:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-comments".
 */
export interface TaskComment {
  id: string;
  task: string | Task;
  author: string | User;
  content: string;
  attachment?: (string | null) | Media;
  mentions?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-activities".
 */
export interface TaskActivity {
  id: string;
  task: string | Task;
  user: string | User;
  action:
    | 'created'
    | 'updated'
    | 'status-changed'
    | 'priority-changed'
    | 'assignee-changed'
    | 'commented'
    | 'attachment-added';
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-files".
 */
export interface ProjectFile {
  id: string;
  name: string;
  description?: string | null;
  project?: (string | null) | Project;
  file: string | Media;
  uploadedBy: string | User;
  category?: ('general' | 'document' | 'design' | 'contract' | 'report' | 'image') | null;
  tags?: string[] | null;
  sharedWith?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'tasks';
        value: string | Task;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'visits';
        value: string | Visit;
      } | null)
    | ({
        relationTo: 'chat-rooms';
        value: string | ChatRoom;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: string | ChatMessage;
      } | null)
    | ({
        relationTo: 'design-requests';
        value: string | DesignRequest;
      } | null)
    | ({
        relationTo: 'code-reviews';
        value: string | CodeReview;
      } | null)
    | ({
        relationTo: 'time-entries';
        value: string | TimeEntry;
      } | null)
    | ({
        relationTo: 'login-logs';
        value: string | LoginLog;
      } | null)
    | ({
        relationTo: 'firewall-rules';
        value: string | FirewallRule;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: string | PushSubscription;
      } | null)
    | ({
        relationTo: 'task-comments';
        value: string | TaskComment;
      } | null)
    | ({
        relationTo: 'task-activities';
        value: string | TaskActivity;
      } | null)
    | ({
        relationTo: 'project-files';
        value: string | ProjectFile;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  avatar?: T;
  role?: T;
  isActive?: T;
  telegramChatId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  status?: T;
  estimatedHours?: T;
  startDate?: T;
  endDate?: T;
  manager?: T;
  members?: T;
  tasks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  priority?: T;
  status?: T;
  assignee?: T;
  assignedBy?: T;
  project?: T;
  dueDate?: T;
  recurrence?: T;
  githubRepo?: T;
  githubBranch?: T;
  dependencies?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  message?: T;
  isRead?: T;
  link?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  address?: T;
  city?: T;
  location?: T;
  tags?: T;
  notes?: T;
  uuid?: T;
  createdBy?: T;
  visits?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits_select".
 */
export interface VisitsSelect<T extends boolean = true> {
  client?: T;
  representative?: T;
  status?: T;
  checkInTime?: T;
  checkOutTime?: T;
  checkInLocation?: T;
  checkOutLocation?: T;
  checkInPhoto?: T;
  distance?: T;
  isValid?: T;
  notes?: T;
  syncedFromOffline?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-rooms_select".
 */
export interface ChatRoomsSelect<T extends boolean = true> {
  name?: T;
  members?: T;
  createdBy?: T;
  messages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  room?: T;
  sender?: T;
  content?: T;
  type?: T;
  attachment?: T;
  mentions?: T;
  replyTo?: T;
  reactions?: T;
  isPinned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-requests_select".
 */
export interface DesignRequestsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  platform?: T;
  status?: T;
  designer?: T;
  requestedBy?: T;
  dueDate?: T;
  designs?:
    | T
    | {
        image?: T;
        note?: T;
        id?: T;
      };
  reviewNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code-reviews_select".
 */
export interface CodeReviewsSelect<T extends boolean = true> {
  title?: T;
  task?: T;
  submittedBy?: T;
  reviewer?: T;
  status?: T;
  githubRepo?: T;
  githubBranch?: T;
  githubPR?: T;
  description?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries_select".
 */
export interface TimeEntriesSelect<T extends boolean = true> {
  user?: T;
  task?: T;
  startTime?: T;
  endTime?: T;
  duration?: T;
  description?: T;
  isRunning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs_select".
 */
export interface LoginLogsSelect<T extends boolean = true> {
  user?: T;
  email?: T;
  success?: T;
  ip?: T;
  userAgent?: T;
  country?: T;
  isTor?: T;
  isVPN?: T;
  isProxy?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firewall-rules_select".
 */
export interface FirewallRulesSelect<T extends boolean = true> {
  type?: T;
  value?: T;
  action?: T;
  description?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  endpoint?: T;
  subscription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-comments_select".
 */
export interface TaskCommentsSelect<T extends boolean = true> {
  task?: T;
  author?: T;
  content?: T;
  attachment?: T;
  mentions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-activities_select".
 */
export interface TaskActivitiesSelect<T extends boolean = true> {
  task?: T;
  user?: T;
  action?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-files_select".
 */
export interface ProjectFilesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  project?: T;
  file?: T;
  uploadedBy?: T;
  category?: T;
  tags?: T;
  sharedWith?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings".
 */
export interface SystemSetting {
  id: string;
  /**
   * Token من @BotFather
   */
  telegramBotToken?: string | null;
  /**
   * بدون @ — مثال: TasklyBot
   */
  telegramBotUsername?: string | null;
  telegramEnabled?: boolean | null;
  smtpHost?: string | null;
  smtpPort?: number | null;
  smtpUser?: string | null;
  smtpPass?: string | null;
  smtpFrom?: string | null;
  emailEnabled?: boolean | null;
  appIcon?: (string | null) | Media;
  appName?: string | null;
  companyName?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings_select".
 */
export interface SystemSettingsSelect<T extends boolean = true> {
  telegramBotToken?: T;
  telegramBotUsername?: T;
  telegramEnabled?: T;
  smtpHost?: T;
  smtpPort?: T;
  smtpUser?: T;
  smtpPass?: T;
  smtpFrom?: T;
  emailEnabled?: T;
  appIcon?: T;
  appName?: T;
  companyName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}