/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    tasks: Task;
    notifications: Notification;
    clients: Client;
    visits: Visit;
    'chat-rooms': ChatRoom;
    'chat-messages': ChatMessage;
    'design-requests': DesignRequest;
    'code-reviews': CodeReview;
    'time-entries': TimeEntry;
    'login-logs': LoginLog;
    'firewall-rules': FirewallRule;
    'task-comments': TaskComment;
    'task-activities': TaskActivity;
    'project-files': ProjectFile;
    'push-subscriptions': PushSubscription;
    'refresh-tokens': RefreshToken;
    'magic-tokens': MagicToken;
    'audit-logs': AuditLog;
    webhooks: Webhook;
    companies: Company;
    leads: Lead;
    deals: Deal;
    products: Product;
    'crm-activities': CrmActivity;
    quotes: Quote;
    invoices: Invoice;
    'service-requests': ServiceRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    projects: {
      tasks: 'tasks';
    };
    clients: {
      visits: 'visits';
    };
    'chat-rooms': {
      messages: 'chat-messages';
    };
    companies: {
      contacts: 'clients';
      deals: 'deals';
    };
    deals: {
      activities: 'crm-activities';
      quotes: 'quotes';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    visits: VisitsSelect<false> | VisitsSelect<true>;
    'chat-rooms': ChatRoomsSelect<false> | ChatRoomsSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    'design-requests': DesignRequestsSelect<false> | DesignRequestsSelect<true>;
    'code-reviews': CodeReviewsSelect<false> | CodeReviewsSelect<true>;
    'time-entries': TimeEntriesSelect<false> | TimeEntriesSelect<true>;
    'login-logs': LoginLogsSelect<false> | LoginLogsSelect<true>;
    'firewall-rules': FirewallRulesSelect<false> | FirewallRulesSelect<true>;
    'task-comments': TaskCommentsSelect<false> | TaskCommentsSelect<true>;
    'task-activities': TaskActivitiesSelect<false> | TaskActivitiesSelect<true>;
    'project-files': ProjectFilesSelect<false> | ProjectFilesSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    'refresh-tokens': RefreshTokensSelect<false> | RefreshTokensSelect<true>;
    'magic-tokens': MagicTokensSelect<false> | MagicTokensSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    webhooks: WebhooksSelect<false> | WebhooksSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'crm-activities': CrmActivitiesSelect<false> | CrmActivitiesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'service-requests': ServiceRequestsSelect<false> | ServiceRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'system-settings': SystemSetting;
  };
  globalsSelect: {
    'system-settings': SystemSettingsSelect<false> | SystemSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  phone?: string | null;
  avatar?: (string | null) | Media;
  role: 'super-admin' | 'supervisor' | 'auditor' | 'sales-rep' | 'programmer' | 'designer' | 'social-media-manager';
  isActive?: boolean | null;
  twoFactorEnabled?: boolean | null;
  twoFactorSecret?: string | null;
  telegramChatId?: string | null;
  /**
   * JSON يضم إعدادات المظهر مثل الوضع الداكن، ترتيب القوائم، الخ
   */
  preferences?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * تجاوز صلاحيات الدور الافتراضي باستخدام JSON
   */
  customPermissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  description?: string | null;
  status: 'planning' | 'active' | 'on-hold' | 'completed' | 'cancelled';
  estimatedHours?: number | null;
  startDate?: string | null;
  endDate?: string | null;
  manager?: (string | null) | User;
  members?: (string | User)[] | null;
  tasks?: {
    docs?: (string | Task)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'programming' | 'field-visit' | 'design' | 'general';
  priority: 'urgent' | 'high' | 'medium' | 'low';
  status: 'new' | 'in-progress' | 'in-review' | 'completed' | 'cancelled';
  assignee?: (string | null) | User;
  assignedBy?: (string | null) | User;
  project?: (string | null) | Project;
  dueDate?: string | null;
  recurrence?: ('none' | 'daily' | 'weekly' | 'monthly') | null;
  githubRepo?: string | null;
  githubBranch?: string | null;
  attachments?: (string | Media)[] | null;
  /**
   * المهام التي يجب إنجازها قبل هذه المهمة
   */
  dependencies?: (string | Task)[] | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  recipient: string | User;
  type:
    | 'task-assigned'
    | 'task-updated'
    | 'comment'
    | 'security-alert'
    | 'visit'
    | 'lead-transferred'
    | 'quote-accepted'
    | 'deal-won'
    | 'deal-lost'
    | 'system';
  title: string;
  message: string;
  isRead?: boolean | null;
  link?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  name: string;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  city?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  tags?: ('vip' | 'new' | 'regular' | 'prospect' | 'inactive')[] | null;
  company?: (string | null) | Company;
  jobTitle?: string | null;
  notes?: string | null;
  uuid?: string | null;
  createdBy?: (string | null) | User;
  visits?: {
    docs?: (string | Visit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  industry?:
    | (
        | 'it'
        | 'trade'
        | 'manufacturing'
        | 'services'
        | 'real-estate'
        | 'healthcare'
        | 'education'
        | 'finance'
        | 'media'
        | 'energy'
        | 'other'
      )
    | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  address?: string | null;
  city?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  status?: ('active' | 'inactive' | 'prospect') | null;
  employeeCount?: ('1-10' | '11-50' | '51-200' | '201-500' | '500+') | null;
  /**
   * تقدير الإيرادات السنوية بالدولار
   */
  annualRevenue?: number | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (string | null) | Media;
  createdBy?: (string | null) | User;
  contacts?: {
    docs?: (string | Client)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  deals?: {
    docs?: (string | Deal)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: string;
  title: string;
  company?: (string | null) | Company;
  contact?: (string | null) | Client;
  stage: 'qualification' | 'proposal' | 'negotiation' | 'won' | 'lost';
  value: number;
  currency?: ('USD' | 'IQD' | 'EUR') | null;
  probability?: number | null;
  assignedTo?: (string | null) | User;
  expectedCloseDate?: string | null;
  source?:
    | (
        | 'website'
        | 'referral'
        | 'social-media'
        | 'advertisement'
        | 'exhibition'
        | 'cold-call'
        | 'converted-lead'
        | 'other'
      )
    | null;
  products?:
    | {
        product: string | Product;
        quantity: number;
        unitPrice: number;
        discount?: number | null;
        id?: string | null;
      }[]
    | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lostReason?: ('price' | 'competitor' | 'delayed' | 'no-interest' | 'budget' | 'other') | null;
  lead?: (string | null) | Lead;
  closedAt?: string | null;
  createdBy?: (string | null) | User;
  activities?: {
    docs?: (string | CrmActivity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  quotes?: {
    docs?: (string | Quote)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'product' | 'service';
  sku?: string | null;
  price: number;
  currency?: ('USD' | 'IQD' | 'EUR') | null;
  category?: string | null;
  image?: (string | null) | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  name: string;
  phone?: string | null;
  email?: string | null;
  companyName?: string | null;
  jobTitle?: string | null;
  source:
    | 'website'
    | 'referral'
    | 'social-media'
    | 'advertisement'
    | 'exhibition'
    | 'cold-call'
    | 'email-campaign'
    | 'partner'
    | 'google-maps'
    | 'other';
  status: 'new' | 'contacted' | 'qualified' | 'unqualified' | 'converted' | 'lost';
  estimatedValue?: number | null;
  assignedTo?: (string | null) | User;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  city?: string | null;
  address?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  category?: string | null;
  priority?: ('A' | 'B' | 'C') | null;
  externalData?: {
    placeId?: string | null;
    mapsUrl?: string | null;
    website?: string | null;
    rating?: number | null;
    reviewCount?: number | null;
  };
  convertedAt?: string | null;
  convertedTo?: {
    client?: (string | null) | Client;
    deal?: (string | null) | Deal;
    company?: (string | null) | Company;
  };
  createdBy?: (string | null) | User;
  /**
   * حذف مؤقت — يمكن استعادته
   */
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-activities".
 */
export interface CrmActivity {
  id: string;
  type: 'call' | 'meeting' | 'email' | 'task' | 'note' | 'visit' | 'presentation';
  subject: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contact?: (string | null) | Client;
  company?: (string | null) | Company;
  deal?: (string | null) | Deal;
  assignedTo?: (string | null) | User;
  scheduledAt?: string | null;
  duration?: number | null;
  callDirection?: ('outgoing' | 'incoming') | null;
  callResult?: ('answered' | 'no-answer' | 'busy' | 'voicemail') | null;
  meetingLocation?: string | null;
  completed?: boolean | null;
  completedAt?: string | null;
  outcome?: string | null;
  attachments?: (string | Media)[] | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: string;
  quoteNumber?: string | null;
  deal?: (string | null) | Deal;
  company?: (string | null) | Company;
  contact?: (string | null) | Client;
  lead?: (string | null) | Lead;
  status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired';
  validUntil?: string | null;
  items: {
    product?: (string | null) | Product;
    description: string;
    quantity: number;
    unitPrice: number;
    discount?: number | null;
    id?: string | null;
  }[];
  currency?: ('USD' | 'IQD' | 'EUR') | null;
  taxRate?: number | null;
  subtotal?: number | null;
  total?: number | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  termsAndConditions?: string | null;
  createdBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits".
 */
export interface Visit {
  id: string;
  client?: (string | null) | Client;
  lead?: (string | null) | Lead;
  representative: string | User;
  status: 'checked-in' | 'checked-out' | 'cancelled';
  outcome?: ('agreed' | 'interested' | 'pending' | 'callback' | 'no-answer' | 'rejected') | null;
  checkInTime: string;
  checkOutTime?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  checkInLocation?: [number, number] | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  checkOutLocation?: [number, number] | null;
  checkInPhoto?: (string | null) | Media;
  distance?: number | null;
  /**
   * يتم التحقق تلقائياً من صحة الموقع
   */
  isValid?: boolean | null;
  attachments?: (string | Media)[] | null;
  notes?: string | null;
  syncedFromOffline?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-rooms".
 */
export interface ChatRoom {
  id: string;
  name: string;
  members: (string | User)[];
  createdBy?: (string | null) | User;
  messages?: {
    docs?: (string | ChatMessage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: string;
  room: string | ChatRoom;
  sender: string | User;
  content?: string | null;
  type?: ('text' | 'image' | 'file') | null;
  attachment?: (string | null) | Media;
  mentions?: (string | User)[] | null;
  replyTo?: (string | null) | ChatMessage;
  reactions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isPinned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-requests".
 */
export interface DesignRequest {
  id: string;
  title: string;
  description?: string | null;
  platform: ('instagram' | 'twitter' | 'facebook' | 'tiktok' | 'linkedin' | 'snapchat')[];
  status: 'requested' | 'in-progress' | 'in-review' | 'approved' | 'rejected' | 'published';
  designer?: (string | null) | User;
  requestedBy?: (string | null) | User;
  dueDate?: string | null;
  designs?:
    | {
        image: string | Media;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code-reviews".
 */
export interface CodeReview {
  id: string;
  title: string;
  task?: (string | null) | Task;
  submittedBy?: (string | null) | User;
  reviewer?: (string | null) | User;
  status: 'pending' | 'in-review' | 'approved' | 'rejected' | 'changes-requested';
  githubRepo?: string | null;
  githubBranch?: string | null;
  githubPR?: string | null;
  description?: string | null;
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries".
 */
export interface TimeEntry {
  id: string;
  user: string | User;
  task: string | Task;
  startTime: string;
  endTime?: string | null;
  duration?: number | null;
  description?: string | null;
  isRunning?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs".
 */
export interface LoginLog {
  id: string;
  user?: (string | null) | User;
  email?: string | null;
  success?: boolean | null;
  ip?: string | null;
  userAgent?: string | null;
  country?: string | null;
  isTor?: boolean | null;
  isVPN?: boolean | null;
  isProxy?: boolean | null;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firewall-rules".
 */
export interface FirewallRule {
  id: string;
  type: 'ip' | 'ip-range' | 'country';
  /**
   * مثال: 192.168.1.1 أو 192.168.1.0/24 أو SA
   */
  value: string;
  action: 'block' | 'allow';
  description?: string | null;
  isActive?: boolean | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-comments".
 */
export interface TaskComment {
  id: string;
  task: string | Task;
  author: string | User;
  content: string;
  attachment?: (string | null) | Media;
  mentions?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-activities".
 */
export interface TaskActivity {
  id: string;
  task: string | Task;
  user: string | User;
  action:
    | 'created'
    | 'updated'
    | 'status-changed'
    | 'priority-changed'
    | 'assignee-changed'
    | 'commented'
    | 'attachment-added';
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-files".
 */
export interface ProjectFile {
  id: string;
  name: string;
  description?: string | null;
  project?: (string | null) | Project;
  file: string | Media;
  uploadedBy: string | User;
  category?: ('general' | 'document' | 'design' | 'contract' | 'report' | 'image') | null;
  tags?: string[] | null;
  sharedWith?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: string;
  user: string | User;
  endpoint: string;
  subscription:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refresh-tokens".
 */
export interface RefreshToken {
  id: string;
  user: string | User;
  token: string;
  expiresAt: string;
  /**
   * User-Agent أو معرّف الجهاز
   */
  device?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magic-tokens".
 */
export interface MagicToken {
  id: string;
  user: string | User;
  token: string;
  expiresAt: string;
  used?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  user?: (string | null) | User;
  action: 'create' | 'update' | 'delete' | 'soft-delete' | 'restore' | 'transfer' | 'login' | 'logout';
  collectionName: string;
  documentId?: string | null;
  /**
   * الحقول التي تم تغييرها
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhooks".
 */
export interface Webhook {
  id: string;
  name: string;
  /**
   * URL الذي سيتم إرسال الأحداث إليه
   */
  url: string;
  events: ('task.created' | 'task.updated' | 'task.deleted' | 'visit.created' | 'client.created' | 'client.updated')[];
  /**
   * سيُستخدم لتوقيع Payload (HMAC-SHA256)
   */
  secret?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  invoiceNumber?: string | null;
  quote?: (string | null) | Quote;
  deal?: (string | null) | Deal;
  client?: (string | null) | Client;
  company?: (string | null) | Company;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  issuedAt?: string | null;
  dueDate?: string | null;
  paidAt?: string | null;
  items: {
    description: string;
    quantity: number;
    unitPrice: number;
    discount?: number | null;
    id?: string | null;
  }[];
  subtotal?: number | null;
  taxRate?: number | null;
  total?: number | null;
  currency?: ('USD' | 'IQD') | null;
  paymentTerms?: string | null;
  notes?: string | null;
  createdBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests".
 */
export interface ServiceRequest {
  id: string;
  companyName: string;
  contactName: string;
  email: string;
  phone: string;
  service?: (string | null) | Product;
  /**
   * يُملأ تلقائياً في حال عدم اختيار منتج
   */
  serviceName?: string | null;
  message?: string | null;
  budget?: ('under-1k' | '1k-5k' | '5k-15k' | '15k-50k' | 'over-50k') | null;
  status?: ('new' | 'reviewed' | 'contacted' | 'converted' | 'rejected') | null;
  convertedToDeal?: (string | null) | Deal;
  internalNotes?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'tasks';
        value: string | Task;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'visits';
        value: string | Visit;
      } | null)
    | ({
        relationTo: 'chat-rooms';
        value: string | ChatRoom;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: string | ChatMessage;
      } | null)
    | ({
        relationTo: 'design-requests';
        value: string | DesignRequest;
      } | null)
    | ({
        relationTo: 'code-reviews';
        value: string | CodeReview;
      } | null)
    | ({
        relationTo: 'time-entries';
        value: string | TimeEntry;
      } | null)
    | ({
        relationTo: 'login-logs';
        value: string | LoginLog;
      } | null)
    | ({
        relationTo: 'firewall-rules';
        value: string | FirewallRule;
      } | null)
    | ({
        relationTo: 'task-comments';
        value: string | TaskComment;
      } | null)
    | ({
        relationTo: 'task-activities';
        value: string | TaskActivity;
      } | null)
    | ({
        relationTo: 'project-files';
        value: string | ProjectFile;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: string | PushSubscription;
      } | null)
    | ({
        relationTo: 'refresh-tokens';
        value: string | RefreshToken;
      } | null)
    | ({
        relationTo: 'magic-tokens';
        value: string | MagicToken;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'webhooks';
        value: string | Webhook;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'deals';
        value: string | Deal;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'crm-activities';
        value: string | CrmActivity;
      } | null)
    | ({
        relationTo: 'quotes';
        value: string | Quote;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'service-requests';
        value: string | ServiceRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  avatar?: T;
  role?: T;
  isActive?: T;
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  telegramChatId?: T;
  preferences?: T;
  customPermissions?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  status?: T;
  estimatedHours?: T;
  startDate?: T;
  endDate?: T;
  manager?: T;
  members?: T;
  tasks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  priority?: T;
  status?: T;
  assignee?: T;
  assignedBy?: T;
  project?: T;
  dueDate?: T;
  recurrence?: T;
  githubRepo?: T;
  githubBranch?: T;
  attachments?: T;
  dependencies?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  message?: T;
  isRead?: T;
  link?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  address?: T;
  city?: T;
  location?: T;
  tags?: T;
  company?: T;
  jobTitle?: T;
  notes?: T;
  uuid?: T;
  createdBy?: T;
  visits?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits_select".
 */
export interface VisitsSelect<T extends boolean = true> {
  client?: T;
  lead?: T;
  representative?: T;
  status?: T;
  outcome?: T;
  checkInTime?: T;
  checkOutTime?: T;
  checkInLocation?: T;
  checkOutLocation?: T;
  checkInPhoto?: T;
  distance?: T;
  isValid?: T;
  attachments?: T;
  notes?: T;
  syncedFromOffline?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-rooms_select".
 */
export interface ChatRoomsSelect<T extends boolean = true> {
  name?: T;
  members?: T;
  createdBy?: T;
  messages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  room?: T;
  sender?: T;
  content?: T;
  type?: T;
  attachment?: T;
  mentions?: T;
  replyTo?: T;
  reactions?: T;
  isPinned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-requests_select".
 */
export interface DesignRequestsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  platform?: T;
  status?: T;
  designer?: T;
  requestedBy?: T;
  dueDate?: T;
  designs?:
    | T
    | {
        image?: T;
        note?: T;
        id?: T;
      };
  reviewNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code-reviews_select".
 */
export interface CodeReviewsSelect<T extends boolean = true> {
  title?: T;
  task?: T;
  submittedBy?: T;
  reviewer?: T;
  status?: T;
  githubRepo?: T;
  githubBranch?: T;
  githubPR?: T;
  description?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries_select".
 */
export interface TimeEntriesSelect<T extends boolean = true> {
  user?: T;
  task?: T;
  startTime?: T;
  endTime?: T;
  duration?: T;
  description?: T;
  isRunning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs_select".
 */
export interface LoginLogsSelect<T extends boolean = true> {
  user?: T;
  email?: T;
  success?: T;
  ip?: T;
  userAgent?: T;
  country?: T;
  isTor?: T;
  isVPN?: T;
  isProxy?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firewall-rules_select".
 */
export interface FirewallRulesSelect<T extends boolean = true> {
  type?: T;
  value?: T;
  action?: T;
  description?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-comments_select".
 */
export interface TaskCommentsSelect<T extends boolean = true> {
  task?: T;
  author?: T;
  content?: T;
  attachment?: T;
  mentions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-activities_select".
 */
export interface TaskActivitiesSelect<T extends boolean = true> {
  task?: T;
  user?: T;
  action?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-files_select".
 */
export interface ProjectFilesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  project?: T;
  file?: T;
  uploadedBy?: T;
  category?: T;
  tags?: T;
  sharedWith?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  endpoint?: T;
  subscription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refresh-tokens_select".
 */
export interface RefreshTokensSelect<T extends boolean = true> {
  user?: T;
  token?: T;
  expiresAt?: T;
  device?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magic-tokens_select".
 */
export interface MagicTokensSelect<T extends boolean = true> {
  user?: T;
  token?: T;
  expiresAt?: T;
  used?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  collectionName?: T;
  documentId?: T;
  changes?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhooks_select".
 */
export interface WebhooksSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  events?: T;
  secret?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  industry?: T;
  phone?: T;
  email?: T;
  website?: T;
  address?: T;
  city?: T;
  location?: T;
  status?: T;
  employeeCount?: T;
  annualRevenue?: T;
  notes?: T;
  logo?: T;
  createdBy?: T;
  contacts?: T;
  deals?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  companyName?: T;
  jobTitle?: T;
  source?: T;
  status?: T;
  estimatedValue?: T;
  assignedTo?: T;
  notes?: T;
  city?: T;
  address?: T;
  location?: T;
  category?: T;
  priority?: T;
  externalData?:
    | T
    | {
        placeId?: T;
        mapsUrl?: T;
        website?: T;
        rating?: T;
        reviewCount?: T;
      };
  convertedAt?: T;
  convertedTo?:
    | T
    | {
        client?: T;
        deal?: T;
        company?: T;
      };
  createdBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  contact?: T;
  stage?: T;
  value?: T;
  currency?: T;
  probability?: T;
  assignedTo?: T;
  expectedCloseDate?: T;
  source?: T;
  products?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        discount?: T;
        id?: T;
      };
  notes?: T;
  lostReason?: T;
  lead?: T;
  closedAt?: T;
  createdBy?: T;
  activities?: T;
  quotes?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  sku?: T;
  price?: T;
  currency?: T;
  category?: T;
  image?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-activities_select".
 */
export interface CrmActivitiesSelect<T extends boolean = true> {
  type?: T;
  subject?: T;
  description?: T;
  contact?: T;
  company?: T;
  deal?: T;
  assignedTo?: T;
  scheduledAt?: T;
  duration?: T;
  callDirection?: T;
  callResult?: T;
  meetingLocation?: T;
  completed?: T;
  completedAt?: T;
  outcome?: T;
  attachments?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  deal?: T;
  company?: T;
  contact?: T;
  lead?: T;
  status?: T;
  validUntil?: T;
  items?:
    | T
    | {
        product?: T;
        description?: T;
        quantity?: T;
        unitPrice?: T;
        discount?: T;
        id?: T;
      };
  currency?: T;
  taxRate?: T;
  subtotal?: T;
  total?: T;
  notes?: T;
  termsAndConditions?: T;
  createdBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  quote?: T;
  deal?: T;
  client?: T;
  company?: T;
  status?: T;
  issuedAt?: T;
  dueDate?: T;
  paidAt?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        discount?: T;
        id?: T;
      };
  subtotal?: T;
  taxRate?: T;
  total?: T;
  currency?: T;
  paymentTerms?: T;
  notes?: T;
  createdBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests_select".
 */
export interface ServiceRequestsSelect<T extends boolean = true> {
  companyName?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  service?: T;
  serviceName?: T;
  message?: T;
  budget?: T;
  status?: T;
  convertedToDeal?: T;
  internalNotes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings".
 */
export interface SystemSetting {
  id: string;
  /**
   * Token من @BotFather
   */
  telegramBotToken?: string | null;
  /**
   * بدون @ — مثال: TasklyBot
   */
  telegramBotUsername?: string | null;
  telegramEnabled?: boolean | null;
  smtpHost?: string | null;
  smtpPort?: number | null;
  smtpUser?: string | null;
  smtpPass?: string | null;
  smtpFrom?: string | null;
  emailEnabled?: boolean | null;
  appName?: string | null;
  companyName?: string | null;
  /**
   * يُعرض في الشريط الجانبي وصفحة تسجيل الدخول (يُفضل PNG شفاف)
   */
  appLogo?: (string | null) | Media;
  /**
   * أيقونة مربعة للتطبيق على الجوال
   */
  appIcon?: (string | null) | Media;
  /**
   * أيقونة تبويب المتصفح (32x32 أو SVG)
   */
  appFavicon?: (string | null) | Media;
  /**
   * اللون الرئيسي للتطبيق (HEX) — مثال: #2563eb
   */
  primaryColor?: string | null;
  /**
   * لون التمييز (HEX) — مثال: #16a34a
   */
  accentColor?: string | null;
  sidebarColor?: ('white' | 'dark' | 'primary') | null;
  loginBackground?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings_select".
 */
export interface SystemSettingsSelect<T extends boolean = true> {
  telegramBotToken?: T;
  telegramBotUsername?: T;
  telegramEnabled?: T;
  smtpHost?: T;
  smtpPort?: T;
  smtpUser?: T;
  smtpPass?: T;
  smtpFrom?: T;
  emailEnabled?: T;
  appName?: T;
  companyName?: T;
  appLogo?: T;
  appIcon?: T;
  appFavicon?: T;
  primaryColor?: T;
  accentColor?: T;
  sidebarColor?: T;
  loginBackground?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}